In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independant = dataset[['age', 'bmi', 'children', 'age', 'bmi', 'children', ]]
independant

      age     bmi  children  age     bmi  children
0      19  27.900         0   19  27.900         0
1      18  33.770         1   18  33.770         1
2      28  33.000         3   28  33.000         3
3      33  22.705         0   33  22.705         0
4      32  28.880         0   32  28.880         0
...   ...     ...       ...  ...     ...       ...
1333   50  30.970         3   50  30.970         3
1334   18  31.920         0   18  31.920         0
1335   18  36.850         0   18  36.850         0
1336   21  25.800         0   21  25.800         0
1337   61  29.070         0   61  29.070         0

[1338 rows x 6 columns]

In [6]:
dependant = dataset[['charges']]
dependant

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split
import xgboost as xgb
x_train,x_test,y_train,y_test = train_test_split(independant,dependant,test_size=0.30,random_state=0)

In [8]:
! pip install xgboost

Requirement already satisfied: xgboost in c:\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from xgboost) (1.16.3)

In [9]:
regressor =xgb.XGBRegressor(n_estimators=200,
                            max_depth=4,
                            learning_rate=0.05,
                            subsample=0.8,
                            colsample_bytree=0.8,
                            random_state=42)
regressoeregressor.fit(x_train,y_train)

NameError: name 'regressoeregressor' is not defined

In [ ]:
y_pred = regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)